<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

  public function research($mot){
    if(is_string($mot)){
      return $this->createQueryBuilder('a')
                      ->where('a.description LIKE ?1')
                      ->orwhere('a.description LIKE ?2')
                      ->orwhere('a.description LIKE ?3')
                      ->setParameter(1, '% '.$mot.' %')
                      ->setParameter(2, $mot.' %')
                      ->setParameter(3, $mot)
                      ->getQuery()
                      ->execute();
    }
  }

}
