user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

create:
    path:     /{_locale}/create
    defaults: { _controller: '\AppBundle\Controller\RedirectController::createAction' }

update:
  path:     /{_locale}/update
  defaults: { _controller: '\AppBundle\Controller\RedirectController::updateAction' }

ajout:
    path:     /{_locale}/ajout
    defaults: { _controller: '\AppBundle\Controller\AnnonceController::ajoutAction' }

lire:
    path:     /{_locale}/read
    defaults: { _controller: '\AppBundle\Controller\AnnonceController::readAction' }

supprimer:
    path:     /{_locale}/supprimer
    defaults: { _controller: '\AppBundle\Controller\AnnonceController::supprimerAction' }

modifier:
    path:     /{_locale}/modifier
    defaults: { _controller: '\AppBundle\Controller\AnnonceController::modifierAction' }

details:
    path:     /{_locale}/details
    defaults: { _controller: '\AppBundle\Controller\AnnonceController::detailsAction' }
